import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import { getCart, clearCart } from "@/api/cart";
import { CartProvider } from "@/components/CartContext";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * This component represents the root layout of the application.
 * @param children - The child components to be rendered within the layout.
 */

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cart = await getCart();

  return (
    <html lang="en">
      <body className={`${roboto.className} mx-6`}>
        <CartProvider cart={cart}>
          <Header />
          <main className="">{children}</main>
        </CartProvider>
      </body>
    </html>
  );
}
